version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ms-email-db
    nvironment:
       POSTGRES_DB: ms_email_db
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: