version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ms-user-db
    nvironment:
       POSTGRES_DB: ms-user-db
       POSTGRES_USER: postgres-user
       POSTGRES_PASSWORD: postgres-password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: